{{- $elasticHost := .Values.elastic_host -}}
{{- $elasticPort := .Values.elastic_port -}}
{{- $elasticScheme := .Values.elastic_sheme -}}
{{- $elasticUsername := .Values.elastic_username -}}
{{- $eslifecycleImage := .Values.eslifecycle_image -}}
{{- with .Values.eslifecycle -}}
{{- range $eslifecycleName, $data := . -}}
{{- $cmName := print "config-" $eslifecycleName -}}
{{- $dplName := print "elastic-indices-lifecycle-" $eslifecycleName -}}
{{- $slackDisplayName := print "rollup-es-" $eslifecycleName -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
data:
  elastic_hosts: {{ $data.elastic_host | default $elasticHost | quote }}
  elastic_port: {{ $data.elastic_port | default $elasticPort | quote }}
  elastic_scheme: {{ $data.elastic_scheme | default $elasticScheme | quote }}
  elastic_username: {{ $data.elastic_username | default $elasticUsername | quote }}
  retention: {{ $data.retention | default "90" | quote }}
  slack_username: {{ $slackDisplayName }}
  log_level: {{ $data.log_level | default "info" | quote }}
  wait_time: {{ $data.wait_time | default "43200" | quote }}
  should_slack: {{ $data.should_slack | default "on" | quote }}
  slack_emoji: {{ $data.slack_emoji | default ":elastic:" | quote }}
  slack_channel: {{ $data.slack_channel | default "#alerting-es" | quote }}
  index_prefixes: {{ $data.index_prefixes | default "" | quote }}
  index_suffixes: {{ $data.index_suffixes | default "logs" | quote }}
  date_format: {{ $data.date_format | default "%Y-%m-%d" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $dplName }}
  labels:
    app: {{ $dplName }}
    app.kubernetes.io/name: {{ $dplName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $dplName }}
      app.kubernetes.io/name: {{ $dplName }}
  template:
    metadata:
      labels:
        app: {{ $dplName }}
        app.kubernetes.io/name: {{ $dplName }}
    spec:
      containers:
        - name: eslifecycle
          image: {{ $eslifecycleImage }}
          env:
            - name: ES_LIFECYCLE_elastic_hosts
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: elastic_hosts
            - name: ES_LIFECYCLE_elastic_port
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: elastic_port
            - name: ES_LIFECYCLE_elastic_scheme
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: elastic_scheme
            - name: ES_LIFECYCLE_elastic_username
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: elastic_username
            - name: ES_LIFECYCLE_elastic_password
              valueFrom:
                secretKeyRef:
                  name: {{ $data.elastic_password_secret | default "elastic-password" | quote }}
                  key: password
            - name: ES_LIFECYCLE_wait_time
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: wait_time
            - name: ES_LIFECYCLE_retention
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: retention
            - name: ES_LIFECYCLE_log_level
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: log_level
            - name: ES_LIFECYCLE_should_slack
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: should_slack
            - name: ES_LIFECYCLE_slack_token
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: token
            - name: ES_LIFECYCLE_slack_username
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: slack_username
            - name: ES_LIFECYCLE_slack_channel
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: slack_channel
            - name: ES_LIFECYCLE_slack_emoji
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: slack_emoji
            - name: ES_LIFECYCLE_date_format
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: date_format
            - name: ES_LIFECYCLE_index_prefixes
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: index_prefixes
            - name: ES_LIFECYCLE_index_suffixes
              valueFrom:
                configMapKeyRef:
                  name: {{ $cmName }}
                  key: index_suffixes
{{ end -}}
{{ end -}}
