{{- with .Values.sealedSecrets }}
{{- range $secretName, $data := . }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $secretName }}
spec:
  {{- with $data.encryptedData }}
  encryptedData:
    {{- toYaml . | nindent 4 }}
  {{- end }} # End with $data.encryptedData
  template:
    metadata:
      name: {{ $secretName }}
      {{- if $data.labels }}
      labels:
      {{- toYaml $data.labels | nindent 8 }}
      {{- end }} # End with $data.labels
      {{- with $data.annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }} # End with $data.annotations
    {{- with $data.type }}
    type: {{ . }}
    {{- end }} # End with $data.type
{{- end }} # End range
{{- end }} # End with .Values.sealedSecrets
